### PR TITLE
Update dockerfile and build

### PR DESCRIPTION
**Pull request by erikh360**

### CODE REVIEW

**Review by jerith — COMMENTED** [review]
Some of the github actions could be updated further. See https://github.com/praekeltfoundation/docker-vumi/blob/master/.github/workflows/build.yaml for an example.

**Comment by jerith** [comment]
There was some discussion on #16 that may be relevant.

**Comment by erikh360** [comment]
ugh I missed that PR, will check

**Review by jerith — APPROVED** [review]

**Comment by jerith** [comment]
You'll need to update the `on:` section in the build YAML for branch and tag builds.

**Comment by erikh360** [comment]
I did, or did I miss something?

**Comment by jerith** [comment]
It's currently this, which only builds commits pushed to `main`:
```
on:
  push:
    branches:
      - main
```

For the branch and tag builds we'd need something like this instead:
```
on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'
```

**Pull request merged**
