### PR TITLE
Switch to no-wheelhouse base image

### PR DESCRIPTION
**Pull request by jerith**
NOTE: I've tested that the image builds successfully, but nothing more than that. Someone still needs to check that it actually works properly.

### CODE REVIEW

**Review by rudigiesler — APPROVED** [review]
Looks good! I see that this repo is also still only pushing to docker hub, not GHCR, do we want to look at changing that too?

**Comment by rudigiesler** [comment]
We can also go up to Python 3.10 if you want to, the CI tests 3.7-3.10

**Comment by jerith** [comment]
Switching to GHCR (or pushing to both GHCR and dockerhub) is definitely worth doing. Adding branch/PR builds would probably also be useful. I'll leave those things to you, though.

Happy to switch to 3.10. We should probably add 3.11 to the base image builds now that it's been out for a while.

**Comment by jerith** [comment]
Apparently psycopg2-binary (the version we use here, at least) doesn't have a binary wheel for py3.10. 🤷

**Comment by rudigiesler** [comment]
Happy to upgrade psycopg2 version, as long as it's compatible with Django 3.2, we're not calling the library directly (just pinned for reproducable builds). Can also stay on Python 3.9 for now.

**Comment by erikh360** [comment]
Closing this because I started https://github.com/praekeltfoundation/flow-results/pull/18

**Pull request closed without merging**
